#!/bin/sh

set -eu
name=${1:?slide名を引数に実行してください}
current_date=`date +%Y/%m/%d`

mkdir $name

LINK="https://vividmuimui.github.io/slides/$name/slides"
if ! grep -e "$LINK" README.md > /dev/null
then
    echo "- $current_date [$name]($LINK)" >> README.md
fi

cd $name

cp ../config.yml ./
cat << EOS >> config.yml
title: $name
meta_properties:
  og:type: "website"
  og:title: $name
  og:description: Slide about '$name'. Generated by reveal-ck. $current_date
  og:url: "https://vividmuimui.github.io/slides/$name/slides"

meta_names:
  twitter:card: "summary"
  twitter:site: "@vivid_muimui"
  twitter:creator: "@vivid_muimui"
  twitter:title: $name
  twitter:description: Slide about '$name'. Generated by reveal-ck. $current_date
EOS

mkdir slides
touch slide.md
reveal-ck generate -f slide.md -d slides
cat ../css/* >> ./slides/css/reveal.css
